def generate_mock_devices():
    return [
        {
            'id': 1,
            'name': 'ESP32',
            'type': 'esp32',
            'status': 'connected',
            'x_position': 0,
            'y_position': 0,
            'config': {}
        },
        {
            'id': 2,
            'name': 'Raspberry Pi',
            'type': 'raspberry_pi',
            'status': 'connected',
            'x_position': 0,
            'y_position': 0,
            'config': {}
        },
        {
            'id': 3,
            'name': 'Arduino',
            'type': 'arduino',
            'status': 'connected',
            'x_position': 0,
            'y_position': 0,
            'config': {}
        },
        {'id': 2, 'name': 'Temperature Sensor', 'type': 'sensor', 'status': 'disconnected', 'x_position': 50, 'y_position': 50, 'config': {}},
        {'id': 3, 'name': 'Humidity Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 100, 'y_position': 100, 'config': {}},
        {'id': 4, 'name': 'Pressure Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 150, 'y_position': 150, 'config': {}},
        {'id': 5, 'name': 'Light Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 200, 'y_position': 200, 'config': {}},
        {'id': 6, 'name': 'Motion Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 250, 'y_position': 250, 'config': {}},
        {'id': 7, 'name': 'Proximity Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 300, 'y_position': 300, 'config': {}},
        {'id': 8, 'name': 'Gas Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 350, 'y_position': 350, 'config': {}},
        {'id': 9, 'name': 'Smoke Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 400, 'y_position': 400, 'config': {}},
        {'id': 10, 'name': 'Sound Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 450, 'y_position': 450, 'config': {}},
        {'id': 11, 'name': 'Vibration Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 500, 'y_position': 500, 'config': {}},
        {'id': 12, 'name': 'Water Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 550, 'y_position': 550, 'config': {}},
        {'id': 13, 'name': 'Soil Moisture Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 600, 'y_position': 600, 'config': {}},
        {'id': 14, 'name': 'Ultrasonic Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 650, 'y_position': 650, 'config': {}},
        {'id': 15, 'name': 'IR Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 700, 'y_position': 700, 'config': {}},
        {'id': 16, 'name': 'Color Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 750, 'y_position': 750, 'config': {}},
        {'id': 17, 'name': 'Gas Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 800, 'y_position': 800, 'config': {}},
        {'id': 18, 'name': 'Pressure Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 850, 'y_position': 850, 'config': {}},
        {'id': 19, 'name': 'Temperature Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 900, 'y_position': 900, 'config': {}},
        {'id': 20, 'name': 'Humidity Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 950, 'y_position': 950, 'config': {}},
        {'id': 21, 'name': 'Light Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1000, 'y_position': 1000, 'config': {}},
        {'id': 22, 'name': 'Motion Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1050, 'y_position': 1050, 'config': {}},
        {'id': 23, 'name': 'Proximity Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1100, 'y_position': 1100, 'config': {}},
        {'id': 24, 'name': 'Gas Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1150, 'y_position': 1150, 'config': {}},
        {'id': 25, 'name': 'Smoke Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1200, 'y_position': 1200, 'config': {}},
        {'id': 26, 'name': 'Sound Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1250, 'y_position': 1250, 'config': {}},
        {'id': 27, 'name': 'Vibration Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1300, 'y_position': 1300, 'config': {}},
        {'id': 28, 'name': 'Water Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1350, 'y_position': 1350, 'config': {}},
        {'id': 29, 'name': 'Soil Moisture Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1400, 'y_position': 1400, 'config': {}},
        {'id': 30, 'name': 'Ultrasonic Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1450, 'y_position': 1450, 'config': {}},
        {'id': 31, 'name': 'IR Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1500, 'y_position': 1500, 'config': {}},
        {'id': 32, 'name': 'Color Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1550, 'y_position': 1550, 'config': {}},
        {'id': 33, 'name': 'Gas Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1600, 'y_position': 1600, 'config': {}},
        {'id': 34, 'name': 'Pressure Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1650, 'y_position': 1650, 'config': {}},
        {'id': 35, 'name': 'Temperature Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1700, 'y_position': 1700, 'config': {}},
        {'id': 36, 'name': 'Humidity Sensor', 'type': 'sensor', 'status': 'unconfigured', 'x_position': 1750, 'y_position': 1750, 'config': {}},

    ]